<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Buggregator\Trap\Tests\Stub\Proto\Metadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
à
message.proto
stub.proto"è
Message

id (
command (	
payload (	.
metadata (2.stub.proto.Message.Metadata&
Metadata
key (	
value (	BQ !Buggregator\\Trap\\Tests\\Stub\\Proto‚*Buggregator\\Trap\\Tests\\Stub\\Proto\\Metadatabproto3'
        , true);

        static::$is_initialized = true;
    }
}

